# test trigger and changes
name: Backend CI - Test, Build and Push Images to ACR # This is a trigger for the CI pipeline to run

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/**'  # Include workflow file changes as well
  workflow_dispatch:

jobs:
  build-and-test: # Trigger CI pipeline
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. Install backend dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt  # Make sure pytest is in this file

      # 4. Run backend tests
      - name: Run backend tests
        run: |
          cd backend
          echo "Running backend tests..."
          pytest

      # 5. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 6. Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 7. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/backend:latest backend

      # 8. Push Docker image to ACR
      - name: Push Docker image to ACR
        run: |
          az acr login --name ${{ secrets.ACR_LOGIN_SERVER }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/backend:latest
